version: '3.9'
services:
  server:
    container_name: server
    depends_on:
      - database
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - POSTGRES_USER=pg
      - POSTGRES_PASSWORD=pass
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - POSTGRES_DB=auth
      - PORT=8080
      - SIGNING_KEY=super_secret

  database:
    container_name: database
    image: postgres:14.8-alpine3.18
    restart: always
    environment:
      - POSTGRES_USER=pg
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=auth
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
